
网络处理类=require("Script/系统处理类/网络处理类")()
系统处理类=require("Script/系统处理类/系统处理类")()
聊天处理类=require("Script/系统处理类/聊天处理类")()
好友消息类=require("Script/系统处理类/好友消息类")()
游戏活动类=require("Script/系统处理类/游戏活动类")()
首席弟子类=require("Script/系统处理类/首席弟子类")()
假人事件类=require("Script/系统处理类/假人事件类")()
小巷子网关=require("Script/系统处理类/小巷子网关")()
夫妻处理类=require("Script/系统处理类/夫妻处理类")()
Dismay=require("Script/Dismay/Dismay")()
开奖系统=require("Script/系统处理类/开奖脚本")()
管理工具类=require("Script/系统处理类/糖果管理类")()
辅助内挂类=require("Script/系统处理类/辅助内挂类")()
糖果专用系统=require("Script/系统处理类/糖果专用系统")()
GM工具类=require("Script/系统处理类/GM工具类")()
简单_兽魂系统=require("Script/角色处理类/简单_兽魂系统")()
系统商城=require("Script/系统处理类/系统商城")()
