require("Script/全局函数类/全局函数")
require("Script/全局函数类/全局循环类")
-- require("Script/全局函数类/数据库类")
require("Script/全局函数类/方法函数类")
require("Script/全局函数类/玩家操作类")
require("Script/全局函数类/玩家数据类")
require("Script/全局函数类/队伍函数类")
require("Script/全局函数类/base")
